name: Push image to docker hub
on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Cache pnpm modules üì¶
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Install and Build üîß
        env:
          APP__ENV: ${{ secrets.APP__ENV }}
          DATABASE__FILEPATH: ${{ secrets.DATABASE__FILEPATH }}
          DATABASE__USER__LAST_NAME: ${{ secrets.DATABASE__USER__LAST_NAME }}
          DATABASE__USER__FIRST_NAME: ${{ secrets.DATABASE__USER__FIRST_NAME }}
          DATABASE__USER__EMAIL: ${{ secrets.DATABASE__USER__EMAIL }}
          DATABASE__USER__PASSWORD: ${{ secrets.DATABASE__USER__PASSWORD }}
          DATABASE__USER__ROLES: ${{ secrets.DATABASE__USER__ROLES }}
          AUTH__SECRET: ${{ secrets.AUTH__SECRET }}
          AUTH__ROLES: ${{ secrets.AUTH__ROLES }}
        run: |
          pnpm install
          cd ./frontend
          pnpm run build

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Docker image üñºÔ∏è
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          cd ./backend
          ./gradlew jib --stacktrace
